server:
  port: 8080

spring:
  datasource:
    #H2
    url: jdbc:h2:mem:todo_list
    #MySQL
    #url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/infinitycode_springboot
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
